### ISSUE TITLE
ValueError: invalid literal for int() with base 10: 'userId'

### ISSUE THREAD

**Issue by SebastianLeborg** [ColeMurray/movie-rec-tutorial#1]
Hello! I've followed the tutorial and I'm getting the following error after submitting the job to the cluster for training:

`INFO:__main__:Loading Datasets from MySQL...
INFO:__main__:Datasets Loaded...
INFO:__main__:Training the ALS model...
17/10/06 16:43:26 WARN org.apache.spark.scheduler.TaskSetManager: Lost task 0.0 in stage 0.0 (TID 0, movrec-cluster-w-0.c.qwiklabs-gcp-4d5327dba5259cbc.internal, executor 1): org.apache.spark.api.python.PythonException: Traceback (most recent call last):
  File "/hadoop/yarn/nm-local-dir/usercache/root/appcache/application_1507307147461_0002/container_1507307147461_0002_01_000002/pyspark.zip/pyspark/worker.py", line 177, in main
    process()
  File "/hadoop/yarn/nm-local-dir/usercache/root/appcache/application_1507307147461_0002/container_1507307147461_0002_01_000002/pyspark.zip/pyspark/worker.py", line 172, in process
    serializer.dump_stream(func(split_index, iterator), outfile)
  File "/hadoop/yarn/nm-local-dir/usercache/root/appcache/application_1507307147461_0002/container_1507307147461_0002_01_000002/pyspark.zip/pyspark/serializers.py", line 268, in dump_stream
    vs = list(itertools.islice(iterator, batch))
  File "/tmp/e248fe9a-9afa-48ff-8add-ba2fc2692d6b/engine.py", line 60, in <lambda>
ValueError: invalid literal for int() with base 10: 'userId'`

Is there some problem with the data format?

**Comment by SebastianLeborg** [comment]
I solved it by deleting the headers in the .csv files.

**Comment by ColeMurray** [comment]
Hello Puffler, 

Issue appears resolved. Closing. Please re open if you have additional questions.
